"""Adjusting book model

Revision ID: 2868dc61d965
Revises: 947a5b24e347
Create Date: 2025-01-30 18:55:23.022619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2868dc61d965'
down_revision: Union[str, None] = '947a5b24e347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
