"""Fix duplicate User table issue

Revision ID: 2948740d7253
Revises: 2b4e661446c2
Create Date: 2025-02-11 19:05:59.504833

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2948740d7253"
down_revision: Union[str, None] = "2b4e661446c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
