"""Fixt UserBookStatus table

Revision ID: 2b4e661446c2
Revises: 56b69f39cacf
Create Date: 2025-02-11 18:53:15.495434

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2b4e661446c2"
down_revision: Union[str, None] = "56b69f39cacf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
