"""Add cover_image_url to BookSearchResult

Revision ID: 370cbc8181c4
Revises: 56b69f39cacf
Create Date: 2025-02-02 19:00:41.063612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370cbc8181c4'
down_revision: Union[str, None] = '56b69f39cacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
