"""Adjusting models for cover image

Revision ID: 6126fe788844
Revises: 2868dc61d965
Create Date: 2025-01-30 19:08:13.503189

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6126fe788844'
down_revision: Union[str, None] = '2868dc61d965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
