"""More authentication added

Revision ID: 7405f071f2c3
Revises: de6ca62108f4
Create Date: 2025-02-03 20:32:48.410447

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '7405f071f2c3'
down_revision: Union[str, None] = 'de6ca62108f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
