"""Google Books ID additions

Revision ID: 82798c201be1
Revises: d7afb931689e
Create Date: 2025-01-30 18:14:37.438501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82798c201be1'
down_revision: Union[str, None] = 'd7afb931689e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('bookid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_book_bookid'), 'book', ['bookid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_bookid'), table_name='book')
    op.drop_column('book', 'bookid')
    # ### end Alembic commands ###
