"""Updated google save model

Revision ID: 9b86ff86f38c
Revises: 676463792f33
Create Date: 2025-01-28 20:33:04.941211

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '9b86ff86f38c'
down_revision: Union[str, None] = '676463792f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
