"""Google Books ID & Removed old versions

Revision ID: d7afb931689e
Revises: 2e3f7780d24b
Create Date: 2025-01-30 18:13:32.780296

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd7afb931689e'
down_revision: Union[str, None] = '2e3f7780d24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
