"""Added Google Books Models

Revision ID: ef2f7e612ca5
Revises: 2e3f7780d24b
Create Date: 2025-01-27 18:50:19.227170

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ef2f7e612ca5'
down_revision: Union[str, None] = '2e3f7780d24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
