name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: uv pip install  # Ensure UV's Python setup is available

      - name: Install the project dependencies
        run: uv sync --all-extras --dev  # Installs all dependencies, including dev

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "ALGORITHM=HS256" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> $GITHUB_ENV
          echo "API_URL=http://localhost:8000" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=dummy_key" >> $GITHUB_ENV
          echo "POSTGRES_USER=test_user" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=test_password" >> $GITHUB_ENV
          echo "POSTGRES_DB=test_db" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///test.db" >> $GITHUB_ENV

      - name: Run tests
        run: uv run pytest --cov=BookTracking
