name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Create uv virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install pytest

      - name: Create .env file
        run: |
          echo "DATABASE_URL=sqlite:///test.db" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Run tests
        run: .venv/bin/python -m pytest --cov=BookTracking
